[[redirects]]
  from = "/project/:id/add"
  to = "/project/index.html"
  status = 200

[[redirects]]
  from = "/project/:id/edit"
  to = "/project/index.html"
  status = 200

[[redirects]]
  from = "/project/:id/tasks"
  to = "/project-tasks/index.html"
  status = 200

[[redirects]]
  from = "/projects/:id/users"
  to = "/project-users/index.html"
  status = 200
